CREATE TABLE IF NOT EXISTS sektor (
    id CHAR(36) PRIMARY KEY,
    nama_sektor VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
