CREATE TABLE IF NOT EXISTS domain (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_domain VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);