-- RISIKO ELIGIBILITY
ALTER TABLE risiko_eligibility
ADD CONSTRAINT fk_eligibility_responden
FOREIGN KEY (responden_id) REFERENCES responden(id)
ON DELETE CASCADE ON UPDATE CASCADE,

ADD CONSTRAINT fk_eligibility_risiko
FOREIGN KEY (risiko_id) REFERENCES risiko(id)
ON DELETE CASCADE ON UPDATE CASCADE;


-- RISIKO ALASAN
ALTER TABLE risiko_alasan
ADD CONSTRAINT fk_alasan_responden
FOREIGN KEY (responden_id) REFERENCES responden(id)
ON DELETE CASCADE ON UPDATE CASCADE,

ADD CONSTRAINT fk_alasan_risiko
FOREIGN KEY (risiko_id) REFERENCES risiko(id)
ON DELETE CASCADE ON UPDATE CASCADE;


-- RISIKO DAMPAK
ALTER TABLE risiko_dampak
ADD CONSTRAINT fk_dampak_responden
FOREIGN KEY (responden_id) REFERENCES responden(id)
ON DELETE CASCADE ON UPDATE CASCADE,

ADD CONSTRAINT fk_dampak_risiko
FOREIGN KEY (risiko_id) REFERENCES risiko(id)
ON DELETE CASCADE ON UPDATE CASCADE;


-- RISIKO PENGENDALIAN
ALTER TABLE risiko_pengendalian
ADD CONSTRAINT fk_pengendalian_responden
FOREIGN KEY (responden_id) REFERENCES responden(id)
ON DELETE CASCADE ON UPDATE CASCADE,

ADD CONSTRAINT fk_pengendalian_risiko
FOREIGN KEY (risiko_id) REFERENCES risiko(id)
ON DELETE CASCADE ON UPDATE CASCADE;


-- PROGRESS
ALTER TABLE survey_progress
ADD CONSTRAINT fk_progress_responden
FOREIGN KEY (responden_id) REFERENCES responden(id)
ON DELETE CASCADE ON UPDATE CASCADE,

ADD CONSTRAINT fk_progress_risiko
FOREIGN KEY (risiko_id) REFERENCES risiko(id)
ON DELETE SET NULL ON UPDATE CASCADE;