ALTER TABLE jawaban_identifikasi
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_proteksi
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_deteksi
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_gulih
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_identifikasi_buffer
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_proteksi_buffer
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_deteksi_buffer
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE jawaban_gulih_buffer
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
