// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "Check if the Survey API is running and healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/survey/edit-requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get survey edit requests. Admin/Staff see all, User sees their own.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Edit Request"
                ],
                "summary": "Get Edit Requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.EditRequestItemResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/edit-requests/{id}": {
            "post": {
                "description": "Approve or reject a request to edit survey data. Admin specifies action (\"approve\" or \"reject\").",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Edit Request"
                ],
                "summary": "Review Edit Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Respondent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Provide 'action' (approve/reject) and optional 'response' string",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid body or respondent ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin or Staff only",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/finish": {
            "post": {
                "description": "Mark survey as completed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Progress"
                ],
                "summary": "Finish Survey",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/navigate": {
            "post": {
                "description": "Navigate to next or previous risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Progress"
                ],
                "summary": "Navigate Survey",
                "parameters": [
                    {
                        "description": "Navigation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NavigateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/progress": {
            "get": {
                "description": "Get current survey progress for the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Progress"
                ],
                "summary": "Get Survey Progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/request-edit": {
            "post": {
                "description": "Request to edit survey data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Edit Request"
                ],
                "summary": "Request Edit",
                "parameters": [
                    {
                        "description": "Edit request reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/responden": {
            "get": {
                "description": "Get all survey respondents (Admin/Staff only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Get All Responden",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.RespondenResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/responden/me": {
            "get": {
                "description": "Get current user's respondent profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Get My Responden Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RespondenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create or update current user's respondent profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Upsert My Responden Profile",
                "parameters": [
                    {
                        "description": "Respondent data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateRespondenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RespondenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/responden/{id}": {
            "get": {
                "description": "Get details of a specific respondent (Admin/Staff only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Get Responden by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Responden ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RespondenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko": {
            "get": {
                "description": "Get all active risks for survey",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Get All Risiko Aktif",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/dampak": {
            "post": {
                "description": "Submit impact of risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Dampak",
                "parameters": [
                    {
                        "description": "Dampak request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DampakRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/eligibility": {
            "post": {
                "description": "Submit eligibility for risk assessment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Eligibility",
                "parameters": [
                    {
                        "description": "Eligibility request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EligibilityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/me": {
            "get": {
                "description": "Get current user's risk assessment data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Get My Risiko Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/pengendalian": {
            "post": {
                "description": "Submit mitigation/control for risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Pengendalian",
                "parameters": [
                    {
                        "description": "Pengendalian request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PengendalianRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/reason": {
            "post": {
                "description": "Submit reason for not having risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Alasan",
                "parameters": [
                    {
                        "description": "Alasan request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AlasanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/{id}": {
            "get": {
                "description": "Get risk assessment data for a specific respondent (Admin/Staff only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Get Risiko Data by Respondent ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Respondent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/save-progress": {
            "post": {
                "description": "Save current risk progress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Survey Progress"
                ],
                "summary": "Save Survey Progress",
                "parameters": [
                    {
                        "description": "Save progress request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NavigateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.AlasanRequest": {
            "type": "object",
            "properties": {
                "alasan": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "string"
                },
                "risiko_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateRespondenRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id_perusahaan": {
                    "type": "string"
                },
                "jabatan": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string"
                },
                "no_telepon": {
                    "type": "string"
                },
                "sertifikat_training": {
                    "type": "string"
                }
            }
        },
        "dto.DampakRequest": {
            "type": "object",
            "properties": {
                "dampak_finansial": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "dampak_hukum": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "dampak_operasional": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "dampak_reputasi": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "frekuensi": {
                    "$ref": "#/definitions/models.FrequencyLevel"
                },
                "responden_id": {
                    "type": "string"
                },
                "risiko_id": {
                    "type": "string"
                }
            }
        },
        "dto.EditRequestItemResponse": {
            "type": "object",
            "properties": {
                "edit_approved_at": {
                    "type": "string"
                },
                "edit_approved_by": {
                    "type": "string"
                },
                "edit_rejected_at": {
                    "type": "string"
                },
                "edit_rejected_by": {
                    "type": "string"
                },
                "edit_request_reason": {
                    "type": "string"
                },
                "edit_request_response": {
                    "type": "string"
                },
                "edit_requested_at": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string"
                },
                "nama_perusahaan": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.EligibilityRequest": {
            "type": "object",
            "properties": {
                "pernah_terjadi": {
                    "type": "boolean"
                },
                "responden_id": {
                    "type": "string"
                },
                "risiko_id": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.NavigateRequest": {
            "type": "object",
            "properties": {
                "current_risk": {
                    "type": "integer"
                },
                "direction": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "string"
                }
            }
        },
        "dto.PengendalianRequest": {
            "type": "object",
            "properties": {
                "ada_pengendalian": {
                    "type": "boolean"
                },
                "deskripsi_pengendalian": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "string"
                },
                "risiko_id": {
                    "type": "string"
                }
            }
        },
        "dto.ProgressResponse": {
            "type": "object",
            "properties": {
                "edit_approved_at": {
                    "type": "string"
                },
                "edit_approved_by": {
                    "type": "string"
                },
                "edit_rejected_at": {
                    "type": "string"
                },
                "edit_rejected_by": {
                    "type": "string"
                },
                "edit_request_reason": {
                    "type": "string"
                },
                "edit_request_response": {
                    "type": "string"
                },
                "edit_requested_at": {
                    "type": "string"
                },
                "is_rejected": {
                    "type": "boolean"
                },
                "langkah_saat_ini": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "string"
                },
                "risiko_id": {
                    "type": "string"
                },
                "selesai": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                }
            }
        },
        "dto.RequestEditRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "dto.RespondenResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "id_perusahaan": {
                    "description": "dari PERUSAHAAN",
                    "type": "string"
                },
                "jabatan": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "description": "dari RESPONDEN",
                    "type": "string"
                },
                "nama_perusahaan": {
                    "type": "string"
                },
                "nama_sektor": {
                    "type": "string"
                },
                "nama_sub_sektor": {
                    "description": "dari JOIN (opsional)",
                    "type": "string"
                },
                "no_telepon": {
                    "type": "string"
                },
                "sertifikat_training": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "dari backend (JWT)",
                    "type": "string"
                }
            }
        },
        "dto.ReviewEditRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"approve\" or \"reject\"",
                    "type": "string",
                    "example": "approve"
                },
                "response": {
                    "type": "string",
                    "example": "Alasan persetujuan atau penolakan"
                }
            }
        },
        "models.FrequencyLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "FrequencySmall",
                "FrequencyMedium",
                "FrequencyLarge",
                "FrequencyVeryLarge"
            ]
        },
        "models.ImpactLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "ImpactNotSignificant",
                "ImpactFairlySignificant",
                "ImpactSignificant",
                "ImpactVerySignificant"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Survey API",
	Description:      "API documentation for Survey service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
