// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "Check if the Survey API is running and healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/survey/edit-requests/{id}": {
            "post": {
                "description": "Approve or reject a request to edit survey data. Admin specifies action (\"approve\" or \"reject\").",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Review Edit Request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Respondent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Provide 'action' (approve/reject) and optional 'response' string",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid body or respondent ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin or Staff only",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/finish": {
            "post": {
                "description": "Complete the survey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Finish Survey",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/navigate": {
            "post": {
                "description": "Navigate through survey steps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Navigate Survey",
                "parameters": [
                    {
                        "description": "Navigate request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NavigateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/progress": {
            "get": {
                "description": "Get current user's survey progress and current step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Get Survey Progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/request-edit": {
            "post": {
                "description": "Request to edit survey data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Request Edit",
                "parameters": [
                    {
                        "description": "Edit request reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/responden": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Hanya admin yang dapat melihat semua data responden",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Ambil semua responden",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/responden/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User hanya dapat melihat data dirinya sendiri",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Ambil data responden milik user login",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Jika belum ada maka create, jika sudah ada maka update (upsert)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Create / Update responden milik user login",
                "parameters": [
                    {
                        "description": "Data Responden",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateRespondenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/responden/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Hanya admin yang dapat melihat detail responden",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responden"
                ],
                "summary": "Ambil responden berdasarkan ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Responden ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/dampak": {
            "post": {
                "description": "Submit impact assessment for risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Dampak",
                "parameters": [
                    {
                        "description": "Dampak request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DampakRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/eligibility": {
            "post": {
                "description": "Submit eligibility for risk assessment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Eligibility",
                "parameters": [
                    {
                        "description": "Eligibility request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EligibilityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/me": {
            "get": {
                "description": "Get current user's risk data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Get My Risiko Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/pengendalian": {
            "post": {
                "description": "Submit control measures for risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Pengendalian",
                "parameters": [
                    {
                        "description": "Pengendalian request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PengendalianRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/reason": {
            "post": {
                "description": "Submit reason for risk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Submit Alasan",
                "parameters": [
                    {
                        "description": "Alasan request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AlasanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/risiko/{id}": {
            "get": {
                "description": "Get risk data by respondent ID (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Get Risiko by Respondent ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Respondent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/survey/save-progress": {
            "post": {
                "description": "Save current survey progress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Risiko"
                ],
                "summary": "Save Progress",
                "parameters": [
                    {
                        "description": "Save progress request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NavigateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.AlasanRequest": {
            "type": "object",
            "properties": {
                "alasan": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "integer"
                },
                "risiko_id": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateRespondenRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id_perusahaan": {
                    "type": "string"
                },
                "jabatan": {
                    "type": "string"
                },
                "nama_lengkap": {
                    "type": "string"
                },
                "no_telepon": {
                    "type": "string"
                },
                "sertifikat_training": {
                    "type": "string"
                }
            }
        },
        "dto.DampakRequest": {
            "type": "object",
            "properties": {
                "dampak_finansial": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "dampak_hukum": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "dampak_operasional": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "dampak_reputasi": {
                    "$ref": "#/definitions/models.ImpactLevel"
                },
                "frekuensi": {
                    "$ref": "#/definitions/models.FrequencyLevel"
                },
                "responden_id": {
                    "type": "integer"
                },
                "risiko_id": {
                    "type": "integer"
                }
            }
        },
        "dto.EligibilityRequest": {
            "type": "object",
            "properties": {
                "pernah_terjadi": {
                    "type": "boolean"
                },
                "responden_id": {
                    "type": "integer"
                },
                "risiko_id": {
                    "type": "integer"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.NavigateRequest": {
            "type": "object",
            "properties": {
                "current_risk": {
                    "type": "integer"
                },
                "direction": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PengendalianRequest": {
            "type": "object",
            "properties": {
                "ada_pengendalian": {
                    "type": "boolean"
                },
                "deskripsi_pengendalian": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "integer"
                },
                "risiko_id": {
                    "type": "integer"
                }
            }
        },
        "dto.ProgressResponse": {
            "type": "object",
            "properties": {
                "edit_approved_at": {
                    "type": "string"
                },
                "edit_approved_by": {
                    "type": "string"
                },
                "edit_rejected_at": {
                    "type": "string"
                },
                "edit_rejected_by": {
                    "type": "string"
                },
                "edit_request_reason": {
                    "type": "string"
                },
                "edit_request_response": {
                    "type": "string"
                },
                "edit_requested_at": {
                    "type": "string"
                },
                "is_rejected": {
                    "type": "boolean"
                },
                "langkah_saat_ini": {
                    "type": "string"
                },
                "responden_id": {
                    "type": "integer"
                },
                "risiko_id": {
                    "type": "integer"
                },
                "selesai": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                }
            }
        },
        "dto.RequestEditRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewEditRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"approve\" or \"reject\"",
                    "type": "string",
                    "example": "approve"
                },
                "response": {
                    "type": "string",
                    "example": "Alasan persetujuan atau penolakan"
                }
            }
        },
        "models.FrequencyLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "FrequencySmall",
                "FrequencyMedium",
                "FrequencyLarge",
                "FrequencyVeryLarge"
            ]
        },
        "models.ImpactLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "ImpactNotSignificant",
                "ImpactFairlySignificant",
                "ImpactSignificant",
                "ImpactVerySignificant"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Survey API",
	Description:      "API documentation for Survey service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
